import dynamic from "next/dynamic";
import type { Metadata } from "next";
import { Suspense } from "react";
import { Inter } from "next/font/google";
import "./globals.css";

// 1. Disable SSR
// 2. Defer loading the Client component

const AsyncLDProvider = dynamic(
  () => import("@/app/components/AsyncWithLDProvider"),
  {
    ssr: false,
  }
);

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense>
          <AsyncLDProvider> {children} </AsyncLDProvider>
        </Suspense>
      </body>
    </html>
  );
}
